// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

void main() async {
  // Initialize Firebase with the options from firebase_options.dart
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaom-noTXy_aB1asu8Ykx78_IFFzOpGMA',
    appId: '1:798805418494:web:0b6a6a232e39992d3360af',
    messagingSenderId: '798805418494',
    projectId: 'utbcafe',
    authDomain: 'utbcafe.firebaseapp.com',
    databaseURL: 'https://utbcafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'utbcafe.appspot.com',
    measurementId: 'G-5JJQS6NTNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeXkQY9NyQl7LLx_DnsVyBdwZPVvZ8Ra8',
    appId: '1:798805418494:android:a33ebf12f8dde8353360af',
    messagingSenderId: '798805418494',
    projectId: 'utbcafe',
    databaseURL: 'https://utbcafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'utbcafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCU2hA4tdfCMvsVJgmfhG4beG1N8-uGE',
    appId: '1:798805418494:ios:44b3716b938ffe993360af',
    messagingSenderId: '798805418494',
    projectId: 'utbcafe',
    databaseURL: 'https://utbcafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'utbcafe.appspot.com',
    iosClientId: '798805418494-oi16iesm2legnhm03qdkgdsldp8cvm1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.utbCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtCU2hA4tdfCMvsVJgmfhG4beG1N8-uGE',
    appId: '1:798805418494:ios:44b3716b938ffe993360af',
    messagingSenderId: '798805418494',
    projectId: 'utbcafe',
    databaseURL: 'https://utbcafe-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'utbcafe.appspot.com',
    iosClientId: '798805418494-oi16iesm2legnhm03qdkgdsldp8cvm1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.utbCafe',
  );
}
